apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.selectorLabel }}
  name: {{ .Values.fullName}}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: http
  selector:
    app: {{ .Values.selectorLabel }}