apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.fullName }}
  labels:
    app: {{ .Values.fullName }}
spec:
  serviceName: {{ .Values.fullName }}
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Values.fullName }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullName }}
    spec:
      containers:
        - image: {{ .Values.container.image }}
          env:
            - name: LISTEN_ADDRESS
              value: "0.0.0.0:{{ .Values.service.port }}"
            - name: SUCCESS_REDIRECT
              value: {{ .Values.uiHost }}/{{ .Values.successRedirect }}
            - name: ERROR_REDIRECT
              value: {{.Values.uiHost}}/{{ .Values.errorRedirect }}
            - name: DB_PATH
              value: "/data"
            - name: AUTH_SERVICE_HOST
              value: "{{ .Values.domain }}"
            - name: MAIL_SERVER_HOST
              value: "{{.Values.smtpServer.host}}"
            - name: MAIL_SERVER_PORT
              value: "{{.Values.smtpServer.port}}"
            - name: MAIL_FROM_ADDRESS
              value: "{{ .Values.mailFrom }}"
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullName }}
                  key: smtp-user
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullName }}
                  key: smtp-pass
          name: {{ .Values.container.name }}
          imagePullPolicy: {{ .Values.container.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          volumeMounts:
            - name: {{ .Values.storage.data.volumeName }}
              mountPath: /data
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.storage.data.volumeName }}
        annotations:
          volume.alpha.kubernetes.io/storage-class: anything
      spec:
        accessModes:
          - {{ .Values.storage.data.accessModes }}
        resources:
          requests:
            storage: {{ .Values.storage.data.storageSize }}