replicasCount: 1
fullName: "platform-ms-keys"
selectorLabel: "platform-ms-keys"
domain : "auth.solenopsys.org"
mailFrom : "register@solenopsys.org"

service:
  port: 8080

storage:
  data:
    volumeName: keys-db-vol
    storageSize: 1Gi
    accessModes: "ReadWriteOnce"

container:
  name: server
  image: registry.solenopsys.org/ms-keys
  pullPolicy: Always



smtpServer:
  host: "email-smtp.eu-west-1.amazonaws.com"
  port: 587
  user: "***" # change it by install parameter
  pass: "***" # change it by install parameter



uiHost: "auth.solenopsys.org"
successRedirect: "/confirm/?state=success"
errorRedirect: "/confirm/?state=error"